ebook_metadata:
  title: ༄༅། །སྤྲུལ་པའི་གཏེར་སྟོན་ཆེན་མོའི་རྣམ་ཐར་གྱི་ས་བོན་ཞལ་གསུང་མ་དང་། གཏེར་འབྱུང་འགའ་ཞིག་འབེལ་གཏམ་སྣ་ཚོགས་བཅས་ཕྱོགས་བསྡོམས་རྒྱལ་བསྟན་ཉིན་བྱེད་འོད་སྣང་ཞེས་བྱ་བ་བཞུགས་སོ།།
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས། འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོ། མཆོག་གླིང་རང་གྲྭ་རྒན་པོ་པདྨ་ཡེ་ཤེས།
  sku: SHE-RTD-006
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - yigchung
web_metadata:
  title:
    en: The Collected Biographies of Chokgyur Dechen Lingpa
    bo: མཆོག་གྱུར་བདེ་ཆེན་གླིང་པའི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས་བཞུགས་སོ།
  collection:
    en: Treasury of Precious Termas–  Book 6
    bo: རིན་ཆེན་གཏེར་མཛོད།–  དེབ། ༦
  author:
    en: Authors:Jamgon Kongtrul Lodro Thaye,Jamyang Khyentse Wangpo
    bo: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་པོ།,འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-RTD-006
  category:
    en: Biography
    bo: རྣམ་ཐར།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-006.epub
  description:
    en: ''
    bo: ''
